### ISSUE TITLE
Unexpected "("

### ISSUE THREAD

**Issue by mittelbach** [8go/coinbash#6] opened 2021-10-20 11:21 UTC
When I call the script, I received:  coinbash.sh: 175: Syntax error: "(" unexpected

**Comment by ptmplop** [comment] 2022-04-06 13:41
run it with bash not sh

**Comment by 8go** [comment] 2022-05-17 17:06
@mittelbach try the new version. Try running it with bash, preferably with GNU bash, version 5.1 or higher.

Thanks @ptmplop with helping out and chiming in.

Closing issue because I cannot reproduce it.

**Closed as completed by 8go** 2022-05-17 17:06 UTC
